SELECT F.CATEGORY, PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT F
JOIN (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유') 
    GROUP BY CATEGORY 
) S ON F.CATEGORY = S.CATEGORY AND F.PRICE = S.MAX_PRICE
ORDER BY PRICE DESC;
